backend/models/User.php
<?php
namespace backend\models;

use Yii;

/**
 * User model
 *
 * @property integer $id
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property integer $point
 * @property integer $host_id
 * @property integer $parent_user
 * @property integer $export_money
 */
class User extends \common\models\User
{

}

common/models/User.php
<?php
namespace common\models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use common\models\LoginInfo;

/**
 * User model
 *
 * @property integer $id
 * @property string $password_hash
 * @property string $password_reset_token
 * @property string $email
 * @property string $auth_key
 * @property integer $status
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $password write-only password
 * @property integer $point
 * @property integer $host_id
 * @property integer $parent_user
 * @property integer $export_money
 */
class User extends ActiveRecord implements IdentityInterface
{
    const STATUS_DELETED = 0;
    const STATUS_ACTIVE = 10;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user}}';
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            ['status', 'default', 'value' => self::STATUS_ACTIVE],
            [['parent_user','export_money'], 'integer'],
            ['status', 'in', 'range' => [self::STATUS_ACTIVE, self::STATUS_DELETED]],
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(Task::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getOrders()
    {
        return $this->hasMany(Order::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getLoginInfoList()
    {
        return $this->hasMany(LoginInfo::className(), ['user_id' => 'id']);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * {@inheritdoc}
     */
    public static function findIdentityByAccessToken($token, $type = null)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }

    /**
     * Finds user by email
     *
     * @param string $email
     * @return static|null
     */
    public static function findByEmail($email)
    {
        return static::findOne(['email' => $email, 'status' => self::STATUS_ACTIVE]);
    }

    /**
     * Finds user by password reset token
     *
     * @param string $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        if (!static::isPasswordResetTokenValid($token)) {
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token,
            'status' => self::STATUS_ACTIVE,
        ]);
    }

    /**
     * Finds out if password reset token is valid
     *
     * @param string $token password reset token
     * @return bool
     */
    public static function isPasswordResetTokenValid($token)
    {
        if (empty($token)) {
            return false;
        }

        $timestamp = (int) substr($token, strrpos($token, '_') + 1);
        $expire = Yii::$app->params['user.passwordResetTokenExpire'];
        return $timestamp + $expire >= time();
    }

    /**
     * {@inheritdoc}
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * {@inheritdoc}
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * {@inheritdoc}
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param string $password password to validate
     * @return bool if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return Yii::$app->security->validatePassword($password, $this->password_hash);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password_hash = Yii::$app->security->generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Yii::$app->security->generateRandomString();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Yii::$app->security->generateRandomString() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    /**
     * Подсчёт поинтов, которые принёс реферал - за всё время
     * @return int
     */
    public function getPointsFromReferal()
    {
        $amount = Order::find()->where(['user_id' => $this->id, 'status' => Order::ORDER_STATUS_PAID])->sum('amount');
        if ($amount) {
            return $amount * 0.1 * Yii::$app->params['costPoint'];  // 10%
        } else {
            return 0;
        }
    }

    /**
     * Получаем сумму выплаты от введеных рефералом денежных средств в текущем месяце.
     * @return int
     */
    public function getMoneyFromReferal()
    {
        $amount = Order::find()->where(['user_id' => $this->id, 'status' => Order::ORDER_STATUS_PAID])->andWhere("MONTH(`date_paid`) = MONTH(NOW()) AND YEAR(`date_paid`) = YEAR(NOW())")->sum('amount');

        if ($amount) {
            return $amount * 0.4; // 40%
        } else {
            return 0;
        }
    }

    /**
     * Получаем часть email до @
     * @return string
     */
    public function getPartEmail()
    {
        preg_match('/^([\w\._]+)@/', $this->email, $matches, PREG_OFFSET_CAPTURE);
        return $matches[1][0];
    }

    public function getOrdersForCurrentMonth()
    {
        $orders = Order::find()->where(['user_id' => $this->id, 'status' => Order::ORDER_STATUS_PAID])->andWhere("MONTH(`date_paid`) = MONTH(NOW()) AND YEAR(`date_paid`) = YEAR(NOW())")->all();

        return $orders;
    }

    /**
     * Зачислём пользователю поинты после оплаты яндекс деньгами. (триггер - пришло оповещение от яндекса об успешной оплате)
     * @param integer $amount
     */
    public function addPointsAfterPaid($amount)
    {
        $this->point = $this->point + $amount * Yii::$app->params['costPoint'];

        if ($this->parent_user) {
            $this->addParentsPoints($amount, $this->parent_user);
        }
    }

    /**
     * Добавляем 10% поинтов от реферала.
     * @param integer $amount
     * @param integer $parenUserId
     */
    private function addParentsPoints($amount, $parenUserId)
    {
        $user = User::findOne($parenUserId);
        $user->point = $user->point + round($amount * Yii::$app->params['costPoint'] * 0.1); // 10%
        $user->save();
    }

    /**
     * проверяем достаточно ли поинтов у пользователя
     * @param integer $budget
     * @return bool
     */
    public function chekPointsAvailable($budget)
    {
        if($this->point >= $budget) {
            return true;
        } else {
            return false;
        }
    }

    /**
     * Вычитаем поинты у юзера с баланса при создании тасков
     * @param int $budget
     */
    public function deductPoints($budget)
    {
        $this->point = $this->point - $budget;
    }

    /**
     * @return null|string
     */
    public function getParentEmail()
    {
        if($this->parent_user) {
            $parentUser = self::findOne($this->parent_user);
            return $parentUser->email;
        } else {
            return null;
        }

    }

    /**
     * Последние 5 раз когда человек залогинился
     * @return array|ActiveRecord[]
     */
    public function getLastLoginInfo()
    {
       return LoginInfo::find()->where(['user_id' => $this->id])->orderBy(['id' => SORT_DESC])->limit(5)->asArray()->all();
    }
}

backend/controllers/UserController.php
<?php

namespace backend\controllers;

use backend\controllers\behaviors\AccessBehavior;
use backend\models\Task;
use Yii;
use backend\models\User;
use backend\models\search\UserSearch;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            AccessBehavior::className(),
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        $taskListQuery = Task::find()->where(['user_id' => $id]);

        $dataProviderTasks = new ActiveDataProvider([
            'query' => $taskListQuery,
            'pagination' => [
                'pageSize' => 1000,
            ],
            'sort' => [
                'defaultOrder' => [
                    'id' => SORT_DESC,
                ]
            ],
        ]);


        return $this->render('view', [
            'model' => $this->findModel($id),
            'dataProviderTasks' => $dataProviderTasks,
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
//    public function actionCreate()
//    {
//        $model = new User();
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        }
//
//        return $this->render('create', [
//            'model' => $model,
//        ]);
//    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

    public function actionHandlerAddPoints($id)
    {
        $model = $this->findModel($id);

        $model->point = intval($model->point) + Yii::$app->params['handler-add-points'];

        if (!Yii::$app->user->isGuest) {
            $model->save();
        }

        return $this->redirect(['index']);
    }
}

backend/views/user/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\User */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'status')->textInput() ?>

    <?= $form->field($model, 'parent_user')->textInput() ?>

    <?= $form->field($model, 'export_money')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model backend\models\search\UserSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'auth_key') ?>

    <?= $form->field($model, 'password_hash') ?>

    <?= $form->field($model, 'password_reset_token') ?>

    <?= $form->field($model, 'email') ?>

    <?php // echo $form->field($model, 'point') ?>

    <?php // echo $form->field($model, 'host_id') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'parent_user') ?>

    <?php // echo $form->field($model, 'export_money') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/user/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model backend\models\User */

$this->title = 'Create User';
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\search\UserSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php Pjax::begin(); ?>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [

            'id',
            //'auth_key',
            //'password_hash',
            //'password_reset_token',
            'email:email',
            'point',
            'host_id',
            'status',
            'created_at:datetime',

            [
                    'label' => 'lastLogins',
                    'value' => function($data) {
                        if ($data->getLastLoginInfo() != []) {
                            $result = '';
                            /* @var $lastlogin backend\models\LoginInfo */
                            foreach ($data->getLastLoginInfo() as $lastlogin ) {
                                $result .= '<p>' . Yii::$app->formatter->asDatetime($lastlogin['datetime_login']) . ' ' . $lastlogin['ip'] . '</p>';
                            }
                            return $result;
                        } return null;
                    },
                    'format' => 'html',
            ],

            //'updated_at:datetime',
            'parent_user',
            'export_money',

            [
                'label' => 'add',
                'value' => function($data) {
                    return "<a href='". Url::to(['user/handler-add-points', 'id' => $data->id]) ."'><span class='glyphicon glyphicon-plus'></span></a>";
                },
                'format' => 'html',
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
    <?php Pjax::end(); ?>
</div>

backend/views/user/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model backend\models\User */

$this->title = 'Update User: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="user-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/user/view.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;
use yii\widgets\DetailView;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $model backend\models\User */
/* @var $dataProviderTasks yii\data\ActiveDataProvider  */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Users', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="user-view">
    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>
    <div class="row">

        <div class="col-md-6">
            <?= DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    //'auth_key',
                    //'password_hash',
                    //'password_reset_token',
                    'email:email',
                    'point',
                    'host_id',
                    'status',
                    'created_at:dateTime',
                    //'updated_at:dateTime',
                    'parent_user',
                    'export_money',
                ],
            ]) ?>
        </div>

        <div class="col-md-6">
            <?php foreach ($model->loginInfoList as $loginInfo): ?>
                <p>
                    <?php Yii::$app->formatter->timeZone = 'UTC' ?>
                    <span class="label label-info"><?= Yii::$app->formatter->asDatetime($loginInfo->datetime_login)?></span>
                    <?php Yii::$app->formatter->timeZone = 'Europe/Moscow' ?>
                    <span class="label label-warning">Москва: <?= Yii::$app->formatter->asDatetime($loginInfo->datetime_login) ?></span>
                    <?php Yii::$app->formatter->timeZone = 'Asia/Bangkok' ?>
                    <span class="label label-success">Таиланд: <?= Yii::$app->formatter->asDatetime($loginInfo->datetime_login) ?></span>
                    ip: <?= $loginInfo->ip ?>
                </p>
            <?php endforeach; ?>
        </div>

    </div>

    <div class="row">
        <div class="col-md-12">

            <?= GridView::widget([
                'dataProvider' => $dataProviderTasks,
                'columns' => [

                    'id',
                    'created:datetime',
                    'user.point',
                    'url:url',
                    'description',
                    'second',
                    'budget',
                    'price',
                    'quantity',
                    'order_quantity',
                    //'type',
                    'status',
                    'rang',

                    //['class' => 'yii\grid\ActionColumn'],
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'urlCreator' => function ($action, $model, $key, $index) {
                            return Url::to(['task/'.$action, 'id' => $model->id]);
                        }
                    ],
                ],
            ]); ?>

        </div>
    </div>

</div>