backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use backend\models\LoginForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->loginAdmin()) {
            return $this->goBack();
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\User;
use frontend\controllers\behaviors\CheckSiteOffBehavior;
use frontend\models\Task;
use Yii;
use yii\base\InvalidParamException;
use yii\helpers\ArrayHelper;
use yii\helpers\VarDumper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use frontend\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            CheckSiteOffBehavior::className(),
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup', 'client', 'cabinet', 'login', 'offer', 'referals'],
                'rules' => [
                    [
                        'actions' => ['signup', 'login', 'random'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout', 'client', 'cabinet', 'offer', 'referals'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'layout' => 'home',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex($id_u = 0)
    {
        $id_u = intval($id_u);
        if ($id_u) {
            Yii::$app->response->cookies->add(new \yii\web\Cookie([
                'name' => 'parent_user',
                'value' => $id_u,
            ]));
        }

        $this->layout = '@frontend/views/layouts/home.php';

        return $this->render('index');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        $this->layout = '@frontend/views/layouts/home.php';

        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect(['/site/cabinet']);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionCabinet()
    {
        if (Yii::$app->user->isGuest) {
            return $this->goHome();
        }
        $user = Yii::$app->user->identity;

        $referals = User::find()->where(['parent_user' => $user->id])->count();

        $completeTask = Task::find()->where(['status' => Task::STATUS_FINISH, 'user_id' => $user->id])->count();
        $inProcessTask = Task::find()->where(['status' => Task::STATUS_WORK, 'user_id' => $user->id])->count();

        $contactForm = new ContactForm();
        if ($contactForm->load(Yii::$app->request->post()) && $contactForm->validate()) {
            if ($contactForm->sendEmail(Yii::$app->params['adminEmail'], $user->id)) {
                Yii::$app->session->setFlash('success', 'Сообщение отправлено.');
            } else {
                Yii::$app->session->setFlash('error', 'Сообщение не отправлено.');
            }
            return $this->refresh();
        }

        return $this->render('cabinet', [
            'completeTask' => $completeTask,
            'inProcessTask' => $inProcessTask,
            'referals' => $referals,
            'contactForm' => $contactForm,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionReferals()
    {
        $currentUser = Yii::$app->user->identity;

        $users = User::find()->where(['parent_user' => Yii::$app->user->identity->getId()])->all();

        return $this->render('referals',[
            'users' => $users,
            'currentUser' => $currentUser,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return mixed
     */
    public function actionOffer()
    {
        return $this->render('offer');
    }

    /**
     * Displays client page.
     *
     * @return mixed
     */
    public function actionClient()
    {
        if(Yii::$app->user->isGuest){
            return $this->redirect(['/']);
        }

        $taskListArray = Task::find()->where(['status' => Task::STATUS_WORK])->asArray()->all();

        if ($taskListArray == []) {
            $task = 0;
        } else {
            $idsActiveTask = ArrayHelper::getColumn($taskListArray, 'id');
            $randomId = $idsActiveTask[array_rand($idsActiveTask, 1)];
            $task = Task::find()->where(['id' => $randomId])->asArray()->one();
        }

        return $this->renderAjax('client', [
            'task' => $task,
        ]);
    }

    public function actionRandom()
    {
        if(isset($_POST['btn-access-key'])) {

            if (isset($_POST['access-key']) && Yii::$app->request->post('access-key') == Yii::$app->params['access-key']) {

                $taskListArray = Task::find()->where(['status' => Task::STATUS_WORK])->asArray()->all();

                if ($taskListArray == []) {
                    $task = 0;
                } else {
                    $idsActiveTask = ArrayHelper::getColumn($taskListArray, 'id');
                    $randomId = $idsActiveTask[array_rand($idsActiveTask, 1)];
                    $task = Task::find()->where(['id' => $randomId])->asArray()->one();
                }

                return $this->renderAjax('random', [
                    'task' => $task,
                ]);
            } else {
                return $this->renderAjax('random');
            }

        } else {
            return $this->renderAjax('random');
        }
    }

    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignup()
    {
        $this->layout = '@frontend/views/layouts/home.php';

        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->redirect(['/site/cabinet']);
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }

    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $this->layout = '@frontend/views/layouts/home.php';

        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Проверьте свою почту и папку спам. Следуйте инструкции в письме');
                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Мы не смоги отправить письмо.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $this->layout = '@frontend/views/layouts/home.php';

        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'Новый пароль установлен.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }
}

frontend/views/site/cabinet.php
<?php

/* @var $this yii\web\View */
/* @var $contactForm frontend\models\ContactForm */
/* @var int $completeTask */
/* @var int $inProcessTask  */
/* @var int $referals */
/* @var int $currentUserId */
/* @var array $cabinetWatchMovie */

use yii\helpers\Url;
use yii\web\JqueryAsset;
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Кабинет';
?>

<!-- Info boxes -->
<div class="row">
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-green"><i class="fa fa-thumbs-o-up"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Завершенные задания</span>
                <span class="info-box-number"><?= $completeTask ?></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->
    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-red"><i class="ion ion-ios-gear-outline"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Задания в работе</span>
                <span class="info-box-number"><?= $inProcessTask ?></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>
    <!-- /.col -->


    <div class="col-md-4 col-sm-6 col-xs-12">
        <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="fa fa-users"></i></span>

            <div class="info-box-content">
                <span class="info-box-text">Рефералы</span>
                <span class="info-box-number"><?= $referals ?></span>
            </div>
            <!-- /.info-box-content -->
        </div>
        <!-- /.info-box -->
    </div>

</div>
<!-- /.row -->


<div class="row">
    <div class="col-md-12">
        <div class="small-box bg-aqua">
            <div class="inner">
                <h3>Видео</h3>
                <p>Добавить задание на просмотр</p>
            </div>
            <div class="icon">
                <i class="fa fa-youtube-play"></i>
            </div>
            <a href="<?= Url::to(['/task/create']) ?>" class="small-box-footer">
                Перейти <i class="fa fa-arrow-circle-right"></i>
            </a>
        </div>
    </div>
</div>


<div class="row">

    <div class="col-md-6">
        <div class="box box-success box-solid collapsed-box">
            <div class="box-header with-border">
                <h3 class="box-title">Как заработать поинты?</h3>


                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                    </button>
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body">

                <p>1) Запустите клиент для автоматического просмотра видео.</p>
                <p>2) Разрешите всплывающие окошки для нашего сайта - что-бы видео открывались.</p>



                <p><a class="run-client" target="_blank" data-url="<?= Url::to(['site/client']) ?>">
                    <i class="fa fa-caret-square-o-right"></i> Запустить клиент
                    <span class="label label-success">v1.1</span>
                    </a>
                </p>
                <div class="callout callout-danger">
                    <p>После того как разрешили всплывающие окна, закройте клиент и запустите заново.</p>
                </div>
                <p><img class="img-responsive" src="/images/vsplivaushie_okna.gif" alt=""></p>


            </div>
            <!-- /.box-body -->
        </div>
    </div>

    <div class="col-md-6">
        <div class="box box-warning box-solid collapsed-box">
            <div class="box-header with-border">
                <h3 class="box-title">Обращение в тех поддержку</h3>

                <div class="box-tools pull-right">
                    <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-plus"></i>
                    </button>
                </div>
                <!-- /.box-tools -->
            </div>
            <!-- /.box-header -->
            <div class="box-body" style="display: none;">
                <?php $form = ActiveForm::begin(['id' => 'contact-form']); ?>

                <?= $form->field($contactForm, 'name')->textInput(['autofocus' => true]) ?>

                <?= $form->field($contactForm, 'email') ?>

                <?= $form->field($contactForm, 'body')->textarea(['rows' => 4]) ?>

                <?= $form->field($contactForm, 'verifyCode')->widget(Captcha::className(), [
                    'template' => '<div class="row"><div class="col-lg-3">{image}</div><div class="col-lg-6">{input}</div></div>',
                ]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'contact-button']) ?>
                </div>

                <?php ActiveForm::end(); ?>
            </div>
            <!-- /.box-body -->
        </div>

    </div>

</div>



<?php $this->registerJsFile("@web/js/cabinet.js", [
    'depends' => JqueryAsset::className(),
]);

frontend/views/site/client.php
<?php

/* @var $this yii\web\View */
/* @var $task frontend\models\Task */

use frontend\assets\AppAsset;
use yii\web\JqueryAsset;

AppAsset::register($this);

$this->title = 'Client 1.0.1';
?>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1>TubePro</h1>
            <p>Клиент для просмотра видео в автоматическом режиме. v1.1</p>
            <p>За каждый просмотр вы получаете 1 поинт</p>
            <p>&nbsp;</p>
            <div class="wrap-btns">
            <?php if ($task == 0): ?>
               <p>Сейчас заданий нет, попробуйте закрыть браузер, и запустить клиент заново через некоторое время.</p>
            <?php else: ?>
                <p>
                    <a class="btn btn-success btn-start-client" href="#" data-tasktime="<?= $task['second'] ?>" data-taskid="<?= $task['id'] ?>" data-url="<?= $task['url'] ?>">Запустить</a>
                    <a class="btn btn-success btn-stop-client" href="#">Остановить</a>
                </p>
                <p class="timer-place"></p>
            <?php endif; ?>
            </div>
        </div>
    </div>
</div>

<?php $this->registerJsFile('@web/js/client.js', [
        'depends' => JqueryAsset::className(),
]);

frontend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>

<header class="masthead height-100vh text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-md-6 mx-auto">

                <h1><?= Html::encode($this->title) ?></h1>

                <div class="alert alert-danger">
                    <?= nl2br(Html::encode($message)) ?>
                </div>

            </div>
        </div>
    </div>
</header>

frontend/views/site/index.php
<?php

/* @var $this yii\web\View */

use yii\helpers\Url;

$this->title = 'Купить, получить просмотры youtube';
?>

<header class="masthead text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-10 mx-auto">
                <h1 class="text-uppercase">
                    <strong>Добавим просмотров на ваш канал</strong>
                </h1>
                <hr>
            </div>
            <div class="col-lg-8 mx-auto">
                <p class="text-faded mb-5">Система обмена просмотрами</p>
                <?php if(Yii::$app->user->isGuest): ?>
                    <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Подробнее</a>
                <?php else: ?>
                    <a class="btn btn-primary btn-xl" href="<?= Url::to(['/site/cabinet'])?>">Перейти в кабинет</a>
                <?php endif ?>
            </div>
        </div>
    </div>
    <?php if( Yii::$app->session->hasFlash('success') ): ?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            <?php echo Yii::$app->session->getFlash('success'); ?>
        </div>
    <?php endif;?>
    <?php if( Yii::$app->session->hasFlash('error') ): ?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            <?php echo Yii::$app->session->getFlash('error'); ?>
        </div>
    <?php endif;?>
</header>

<section class="bg-primary" id="about">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <h2 class="section-heading text-white">Попробуйте совершенно бесплатно</h2>
                <hr class="light my-4">
                <p class="text-faded mb-4">Добавьте видео и получайте просмотры реальных людей</p>
                <?php if (Yii::$app->user->isGuest): ?>
                    <a class="btn btn-light btn-xl" href="<?= Url::to(['/site/signup']) ?>">Попробовать</a>
                <?php endif; ?>
            </div>
        </div>
    </div>
</section>

<section id="services">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <h2 class="section-heading">Как всё устроено</h2>
                <hr class="my-4">
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-diamond text-primary mb-3 sr-icons"></i>
                    <h3 class="mb-3">Добавьте ссылку на ваше видео</h3>
<!--                    <p class="text-muted mb-0">Просто скопируйте ссылку</p>-->
                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-dollar text-primary mb-3 sr-icons"></i>
                    <h3 class="mb-3">Установите бюджет</h3>

                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-eye text-primary mb-3 sr-icons"></i>
                    <h3 class="mb-3">Получайте просмотры</h3>

                </div>
            </div>
            <div class="col-lg-3 col-md-6 text-center">
                <div class="service-box mt-5 mx-auto">
                    <i class="fa fa-4x fa-heart text-primary mb-3 sr-icons"></i>
                    <h3 class="mb-3"><?= Yii::$app->params['defaultPointsSignup'] ?> поинтов в подарок</h3>

                </div>
            </div>
        </div>
    </div>
</section>

<section class="bg-dark text-white">
    <div class="container text-center">
        <h2 class="mb-4">Получить бесплатные просмотры</h2>
        <?php if (Yii::$app->user->isGuest): ?>
            <a class="btn btn-light btn-xl sr-button" href="<?= Url::to(['/site/signup']) ?>">Регистрация</a>
        <?php endif; ?>
    </div>
</section>

<section id="contact">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 mx-auto text-center">
                <h2 class="section-heading">Остались вопросы</h2>
                <hr class="my-4">
            </div>
        </div>
        <div class="row justify-content-md-center">
            <div class="col-md-4 text-center">
                <i class="fa fa-envelope-o fa-3x mb-3 sr-contact"></i>
                <p>&#104;&#101;&#108;&#108;&#111;&#64;&#116;&#117;&#98;&#101;&#112;&#114;&#111;&#46;&#114;&#117;</p>
            </div>
        </div>
    </div>
</section>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;

$this->title = 'Войти в кабинет';

?>

<header class="masthead height-100vh text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-lg-8 mx-auto">

                <h1 class="text-uppercase"><?= Html::encode($this->title) ?></h1>

                <?php if (Yii::$app->params['registration-work'] == 1): ?>

                    <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                        <?= $form->field($model, 'email')->textInput(['autofocus' => true, 'placeholder' => 'Email'])->label(false) ?>

                        <?= $form->field($model, 'password')->passwordInput(['placeholder' => 'Пароль'])->label(false) ?>

                        <?= $form->field($model, 'rememberMe')->checkbox() ?>

                        <div style="margin:1em 0">
                            Восстановить пароль <?= Html::a('перейти', ['site/request-password-reset']) ?>.
                        </div>

                        <div class="form-group">
                            <?= Html::submitButton('Вход', ['class' => 'btn btn-warning btn-xl', 'name' => 'login-button']) ?>
                        </div>

                    <?php ActiveForm::end(); ?>

                <?php else: ?>

                    <p>Профилакти. попробуйте зайти позже</p>

                <?php endif ?>

            </div>
        </div>
    </div>
</header>

frontend/views/site/offer.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $users common\models\User[] */
/* @var $currentUser common\models\User */

$this->title = 'Правила сервиса';
?>

<h1><?= Html::encode($this->title) ?></h1>

<div class="row">
    <div class="col-md-12">
        <div class="box box-solid">
            <div class="box-body">
                <h4 style="background-color:#f7f7f7; font-size: 18px; text-align: center; padding: 7px 10px; margin-top: 0;">

                </h4>
                <div class="media">
                    <div class="media-body pravila-servica">

                            <p>Регистрируясь в системе TubePro, Вы соглашаетесь с правилами сервиса.<br>
                                Настоятельно рекомендуем ознакомиться с ними и соблюдать их в течение всего времени.
                            </p>
                            <h4>1. Пользователи</h4>
                            <ul>
                                <li><b>1.1.</b> Регистрируясь на сайте, Вы указываете логин (email) и пароль.</li>
                                <li><b>1.2.</b> Указывая e-mail, Вы автоматически разрешаете отсылать Вам письма. Если e-mail не рабочий, мы можем отказать Вам в предоставлении услуг.</li>

                                <li><b>1.3.</b> Администрация вправе заблокировать Ваш аккаунт при нарушении правил.</li>
                            </ul>
                            <h4>2. Задания</h4>
                            <ul>
                                <li><b>2.1.</b> Выполняя задание, например «подписаться на канал», вы не должны отписываться в дальнейшем. В таком случае, мы вправе списать с Вас любое количество баллов или заблокировать аккаунт.</li>
                                <li><b>2.2.</b> Запрещено размещать задания, где присутствует "раздача голосов, накрутка голосов, магия, порча, заработок, пиар, продажа/покупка аккаунтов, розыгрыши чего-либо, прогнозы на спорт, порно, раскрутка и продвижение с помощью других сервисов", а так-же, любая другая информация запрещенная законодательством РФ.</li>
                                <li><b>2.3.</b> Запрещено использовать краденные профили для продвижения, а так же профили с непонятными именами.</li>
                                <li><b>2.4.</b> Мы не даем Вам никаких гарантий, что заказанная услуга будет выполнена в срок. Всё зависит от объемов заказа и количества пользователей в онлайне.</li>
                                <li><b>2.5.</b> Запрещено использовать свой аккаунт от YouTube на других сервисах/программах для накрутки, так как пользуясь сторонними сервисами/программами, страница YouTube может быть заблокирована из-за некачественной накрутки, предоставляемой другими сервисами. Нарушив этот пункт, мы вправе заблокировать Ваш аккаунт на сервисе навсегда и занести Ваши ссылки в черный список.</li>
                                <li><b>2.6.</b> Запрещено выполнять больше чем: 60 просмотров, 30 лайков и комментов, 4 подписчиков для 1 IP за час.</li>
                                <li><b>2.7.</b> Одновременно нельзя накручивать один и тот же ролик.</li>
                                <li><b>2.8.</b> Запрещено противодействовать работе сервиса, путем установки ограничений на YouTube - устанавливать модерацию комментариев, скрывать отображение лайков или подписчиков, ограничивать доступ к видео.</li>
                                <li><b>2.9.</b> Запрещено писать спам (ссылки на свои ролики, ссылки на сторонние сайты, предложения взаимной подписки, нецензурные фразы, предложения быстрого зароботка, неадекватный набор букв или символов, повторяющиеся сообщения) в комментариях на ютубе к задачам в нашей системе. </li>
                            </ul>
                            <h4>3. Реферальная программа</h4>
                            <ul>
                                <li><b>3.1.</b> Приглашая друга по реферальной ссылке, Вы будете получать на счет 10% от баллов, полученных рефералом при покупке поинтов.</li>
                                <li><b>3.2.</b> Приглашенные друзья должны быть активными на сервисе. В случае неактивности, мы вправе удалить реферала и списать за него полученные баллы.</li>
                            </ul>
                            <h4>4. Платные услуги</h4>
                            <ul>
                                <li><b>4.1.</b> Приобретая любую платную услугу на TubePro, Вы соглашаетесь с тем, что потраченные средства НЕ могут быть возвращены назад.</li>
                                <li><b>4.2.</b> В случае, если Ваш аккаунт на сервисе заблокировали за нарушение какого-либо пункта в то время, когда у Вас действует платная услуга, Вы не вправе требовать возврата средств.</li>
                            </ul>
                            <h4>5. Заключительные положения</h4>
                            <ul>
                                <li><b>5.1.</b> Услуги системы оказываются «как есть» и «при возможности». TubePro не предоставляет никаких гарантий, прямо или косвенно, включая, помимо прочего, гарантии бесперебойной работы системы, гарантии качества услуг, пригодности их для той или иной цели и отсутствие нарушений.</li>
                                <li><b>5.2.</b> TubePro оставляет за собой право в любой момент изменить, приостановить или прекратить предоставление услуг полностью или частично, предварительно уведомив, либо без предварительного уведомления.</li>
                                <li><b>5.3.</b> Администрация сервиса оставляет за собой право изменять правила без уведомления в любой момент времени.</li>
                            </ul> <div class="row">
                                <div class="col-lg-12">
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Восстановить пароль';
$this->params['breadcrumbs'][] = $this->title;
?>

<header class="masthead height-100vh text-center text-white d-flex">
    <div class="container my-auto">
        <div class="row">
            <div class="col-md-4 mx-auto">

                <h2 class="text-uppercase"><?= Html::encode($this->title) ?></h2>
                <p>На указанный email придёт ссылка для восстановления.</p>
                <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                    <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                    <div class="form-group">
                        <?= Html::submitButton('Отправить', ['class' => 'btn btn-primary']) ?>
                    </div>

                <?php ActiveForm::end(); ?>

            </div>
        </div>
    </div>
</header>